services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: pgvector_container
    environment:
      - 'POSTGRES_DB=${PS_DB_NAME}'
      - 'POSTGRES_PASSWORD=${PS_DB_PASSWORD}'
      - 'POSTGRES_USER=${PS_DB_USER}'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    networks:
      - db_network
    volumes:
      - ai_cust_supp_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - db_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: always

networks:
  db_network:
    driver: bridge

volumes:
  ai_cust_supp_postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local