spring:
  application:
    name: client
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
        distance-type: COSINE_DISTANCE
      redis:
        uri: redis://localhost:6379
        index-name: semantic-cache-index
        prefix: "cache:"
        initialize-schema: true
    vectorstore-redis-semantic-cache:
      enabled: true
      threshold: 0.7
      ttl: 3600s
        
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: ${PS_DB_URL:jdbc:postgresql://localhost:5432/aicustomersupportdb}
    username: ${PS_DB_USER:postgres}
    password: ${PS_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

document-loader:
  file-allowed-content-types:
    - "text/markdown"
    - "text/plain"
    - "application/pdf"
    - "text/csv"
    - "text/html"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    - "application/vnd.ms-excel"
    - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    - "application/vnd.ms-powerpoint"
    - "application/vnd.openxmlformats-officedocument.presentationml.presentation"
  chunk-size: 200
  chunk-max-num: 600
  min-chunk-size-chars: 100

test:
  relevancy:
    min-score: 0.7

audit:
  token-usage:
    enabled: true

similarity-search:
  top-k: 3
  threshold: 0.7